packages:
  - apps/*
  - adapters/*
  - packages/*

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - miniflare@5.20260831.0-alpha
  - wrangler@4.128.0

blockExoticSubdeps: true
trustPolicy: no-downgrade
strictDepBuilds: true
allowBuilds:
  deno: true
  esbuild: true
  supabase: true
  vue-demi: true
  workerd: true
