-- Generated by scripts/sync-migrations.mjs. Do not edit.
begin;

do $$
declare
  v_updated integer;
begin
  update one_fetch.migration_history as history
  set checksum = source.checksum
  from (values
    ('202609040001', '39bb47b3c973b575676f5004ee1b018f466763102045fb1bece37f6d27bc0510'),
    ('202609040002', '7dbc55c50491e9b508441a338966547a017d8210730daad13bb6f8c3f859d63f'),
    ('202609040003', '3621e5ca5fe199a5d4fab73d7df9e450566c524b76f951e32ca5e8b567ca8546'),
    ('202609040004', '87a661ff08ae6ea521512620d0121c3f4053286302119e0ed3bf8eb63448c1be'),
    ('202609040005', 'e643698c9dbf74acd57bf4d43b37b5edea4acc554b611bec461634c7ce90f592'),
    ('202609040006', '4eb74e19ffff656e64d9e81797e67dca408e0d7f433d1f42e97bf0964a6ab791'),
    ('202609040007', 'b96eebcb63f0b69fdf46ea057f51c1928dac974591bf9b6365eca90c8efbc883'),
    ('202609040008', 'c3a66b2d1a4a5c0ea8694cfba655b5438c6d4b8cacf518bfed869d77fbafb265')
  ) as source(version, checksum)
  where history.version = source.version;
  get diagnostics v_updated = row_count;
  if v_updated <> 8 then
    raise exception using errcode = 'P0001', message = 'migration_history_incomplete';
  end if;
end;
$$;

create or replace function public.of_get_migration_integrity()
returns jsonb
language sql
stable
security definer
set search_path = one_fetch, pg_temp
as $$
  select coalesce(jsonb_agg(
    jsonb_build_object('version', version, 'checksum', checksum)
    order by version
  ), '[]'::jsonb)
  from migration_history;
$$;

revoke all on function public.of_get_migration_integrity()
  from public, anon, authenticated;
grant execute on function public.of_get_migration_integrity() to service_role;

insert into one_fetch.migration_history (version, checksum)
values ('202609040009', '925160ccb5c7ff9477e3b8034853690dcc0f239d358ff5c72af618b9ff2e5a71');

commit;
