// Generated by scripts/sync-migrations.mjs. Do not edit.
export const SUPABASE_MIGRATION_CHECKSUM_ALGORITHM =
  "self-zeroed-sha256-v1" as const;
export const SUPABASE_MIGRATION_HISTORY = [
  {
    version: "202609040001",
    file: "202609040001_schema.sql",
    checksum:
      "fa2880cabc22ef229c73da48343050f28b6f04cd1e99ca0be9e006b169035ed2",
    artifactSha256:
      "2d828e88a4238cf4793ec70d7eca5f7ed272ebaf346e127f3fc5cd5993fd4b53",
    bytes: 10153,
  },
  {
    version: "202609040002",
    file: "202609040002_auth.sql",
    checksum:
      "aacb3a7bf0d2e30679fab5dca5d2ef883ce8a59053d796fced39290a469c6450",
    artifactSha256:
      "be0430f4550d3c4012a9e2639130aba06862114c66143c14a2a5224fb5bb1662",
    bytes: 13034,
  },
  {
    version: "202609040003",
    file: "202609040003_config_audit.sql",
    checksum:
      "e1b544260fdecf4194c61b74c400ace390019ff1444d451745d4caf9f66e043b",
    artifactSha256:
      "5588b445fbc1ffc090a5369c44b7ee7a4e39fde54cd46d46dbdd165b02aa49d4",
    bytes: 5889,
  },
  {
    version: "202609040004",
    file: "202609040004_quota.sql",
    checksum:
      "5a64d5913d0abd63363c91932b91a1e010ce6782a08db21bb73a4bd88313a24e",
    artifactSha256:
      "b0cd07ec53b6979f9d598015e956e5004b0b66d9c262d8b90eedf9096235765a",
    bytes: 5753,
  },
  {
    version: "202609040005",
    file: "202609040005_canonical_control.sql",
    checksum:
      "8931f2f241e4104b9941247fa341cabc4f44f333c2a55401775301fe54a1a532",
    artifactSha256:
      "13c9f88e3d89e26f8b167d0a4f96b05c446a114af3ee8564d3d4debc73b41500",
    bytes: 3680,
  },
  {
    version: "202609040006",
    file: "202609040006_auth_safety.sql",
    checksum:
      "078ec284c90e752d5702a8a913688dd9731db9304b7450c80c2e50f095ae0c7f",
    artifactSha256:
      "fac78bece57c2b8229224fa03f2518459e39daac74d41914a4214db3f6405a21",
    bytes: 3248,
  },
  {
    version: "202609040007",
    file: "202609040007_execution_lifecycle.sql",
    checksum:
      "aa1d8206d0a25c5d4e592a4cf278a97c7fbb70a65584a4920ce3f0bf6e2c1371",
    artifactSha256:
      "9cb0b68ac109a56dd74e32e8ba58a03c12c3d67370e864abc0188a46de543e89",
    bytes: 13280,
  },
  {
    version: "202609040008",
    file: "202609040008_control_hardening.sql",
    checksum:
      "85ceb468f5a19e9370a768ce1d864f36adb6bc100f0da96842f549996f17eb76",
    artifactSha256:
      "52aac57f020793608eacbc2aaa1897a00a2fc30447f8fcb9eb8f8ebd6784bc39",
    bytes: 13947,
  },
  {
    version: "202609040009",
    file: "202609040009_migration_integrity.sql",
    checksum:
      "7d9ac8e564fcf7fd3d931387a1284d543830aa6c8d0174ce8d4c36de4adc7c31",
    artifactSha256:
      "94a79a843eb483f23126017cad307ee368ffe36b6df37dfc8c0af611bda7c94e",
    bytes: 762,
  },
  {
    version: "202609040010",
    file: "202609040010_deployment_cas.sql",
    checksum:
      "beffe86cc7796d33d13f0584e467be0cfe243629f45b1aa3f806c159a36141e0",
    artifactSha256:
      "cb1ea059fbec30b2a969e4278d12f30d23a9d107a2a30caaea494ae27ada8a50",
    bytes: 7125,
  },
] as const;
