import {
  decodeResponseMetadata,
  ONE_FETCH_RESPONSE_HEADER,
} from "@one-fetch/protocol";
import { verifySignedResponseMetadata } from "@one-fetch/core";
import hosted from "../../../../../packages/core/test/fixtures/supabase-ingress.json" with { type: "json" };
import {
  boundPathRequest,
  pathHarness,
  pathToken,
  targetOrigin,
} from "./path-test-support.ts";

function assert(value: unknown, message: string): asserts value {
  if (!value) throw new Error(message);
}

// These pairs are actual hosted Function observations, not output generated by
// the validator. This handler test still uses a synthetic database/upstream.
for (const [id, original, observed] of hosted.cases) {
  Deno.test(
    `recorded ingress ${id} restores exact upstream bytes`,
    async () => {
      assert(original && observed, "Incomplete ingress fixture");
      const { handler, environment, waitForReport } = await pathHarness();
      const originalFetch = globalThis.fetch;
      let upstreamCalls = 0;
      globalThis.fetch = (input) => {
        upstreamCalls += 1;
        const url = new URL(input instanceof Request ? input.url : input);
        assert(
          url.origin === targetOrigin,
          "Binding replaced target authority",
        );
        return Promise.resolve(new Response(`${url.pathname}${url.search}`));
      };
      try {
        const response = await handler(
          boundPathRequest(environment.gatewayBaseUrl, observed, original),
        );
        const signed = decodeResponseMetadata(
          response.headers.get(ONE_FETCH_RESPONSE_HEADER) ?? "",
        );
        assert(signed.outcome === "target", "Restored request was rejected");
        assert(
          await verifySignedResponseMetadata(signed, {
            token: pathToken,
            requestId: signed.requestId,
            nonce: signed.nonce,
          }),
          "Target response signature invalid",
        );
        assert(
          (await response.text()) === original,
          "Original spelling changed",
        );
        assert(upstreamCalls === 1, "Unexpected upstream count");
        await waitForReport();
      } finally {
        globalThis.fetch = originalFetch;
      }
    },
  );
}

Deno.test(
  "unknown query rewrites are signed denials before quota or upstream",
  async () => {
    const invalid = [
      ["/echo?x=hello+world", "/echo?x=hello%20world"],
      ["/echo?x=%2b", "/echo?x=+"],
      ["/hello%20world?x=1", "/hello+world?x=1"],
      ["/echo?x=1&x=2", "/echo?x=2&x=1"],
      ["/echo?x=&empty", "/echo?x=&empty="],
      ["/echo?x=1&&x=2", "/echo?x=1&x=2"],
      ["/echo?x=%26admin%3Dtrue", "/echo?x=&admin=true"],
      ["/echo?x=%2520", "/echo?x=+"],
      ["/echo?x=%FF", "/echo?x=%EF%BF%BD"],
    ];
    const originalFetch = globalThis.fetch;
    let upstreamCalls = 0;
    globalThis.fetch = () => {
      upstreamCalls += 1;
      throw new Error("Unexpected upstream");
    };
    try {
      for (const [original, observed] of invalid) {
        assert(original && observed, "Incomplete rejection fixture");
        const { handler, environment, calls } = await pathHarness();
        const response = await handler(
          boundPathRequest(environment.gatewayBaseUrl, observed, original),
        );
        const signed = decodeResponseMetadata(
          response.headers.get(ONE_FETCH_RESPONSE_HEADER) ?? "",
        );
        assert(
          signed.outcome === "relay-error",
          "Mismatch became target result",
        );
        assert(signed.error?.code === "invalid_metadata", "Wrong denial code");
        assert(
          await verifySignedResponseMetadata(signed, {
            token: pathToken,
            requestId: signed.requestId,
            nonce: signed.nonce,
          }),
          "Denial signature invalid",
        );
        assert(
          !calls.includes("of_acquire_execution"),
          "Mismatch acquired quota",
        );
      }
      assert(upstreamCalls === 0, "Unknown query rewrite reached upstream");
    } finally {
      globalThis.fetch = originalFetch;
    }
  },
);
