begin;
create extension if not exists pgtap with schema extensions;
select plan(40);

select has_schema('one_fetch', 'internal schema exists');
select has_table('one_fetch', 'instance_state', 'instance table exists');
select has_table('one_fetch', 'admins', 'admin table exists');
select has_table('one_fetch', 'sessions', 'session table exists');
select has_table('one_fetch', 'execution_tokens', 'execution token table exists');
select has_table('one_fetch', 'audit_events', 'audit table exists');
select has_table('one_fetch', 'login_throttles', 'login throttle table exists');
select has_table('one_fetch', 'execution_reports', 'short-term report table exists');
select has_column('one_fetch', 'execution_reports', 'lease_id', 'reports retain the finalized lease identity');
select has_table('one_fetch', 'quota_windows', 'quota table exists');
select has_function('public', 'of_bootstrap_admin', array['uuid','text','text','text','jsonb','jsonb'], 'bootstrap RPC exists');
select has_function('public', 'of_update_config', array['uuid','bigint','text','jsonb','text[]','jsonb'], 'config RPC exists');
select has_function('public', 'of_acquire_execution', array['uuid','text','text','bigint','integer'], 'quota RPC exists');
select has_function('public', 'of_get_execution_report', array['uuid','uuid'], 'report lookup binds the execution token');
select has_function('public', 'of_list_sessions', array['uuid','uuid'], 'canonical session list RPC exists');
select has_function('public', 'of_get_admin_for_password_change', array['uuid'], 'password verification RPC exists');
select has_function('public', 'of_change_password', array['uuid','uuid','text','text','jsonb'], 'transactional password change RPC exists');
select has_function('public', 'of_issue_session', array['uuid','text','boolean','uuid','text','text','timestamptz','timestamptz','text','text','jsonb'], 'session issue RPC uses login compare-and-swap');
select has_function('public', 'of_begin_login_attempt', array['text','text','jsonb'], 'login throttle RPC exists');
select has_function('public', 'of_begin_auth_source_attempt', array['text','text','integer','jsonb'], 'generic auth source throttle RPC exists');
select has_function('public', 'of_bootstrap_admin_session', array['uuid','uuid','uuid','text','text','text','jsonb','uuid','text','text','timestamptz','timestamptz','text','text','jsonb','jsonb','jsonb'], 'atomic bootstrap RPC exists');
select has_function('public', 'of_issue_session_guarded', array['uuid','text','boolean','uuid','text','text','timestamptz','timestamptz','text','text','text','text','jsonb'], 'guarded login session RPC exists');
select has_function('public', 'of_rotate_refresh_audited', array['text','text','text','timestamptz','timestamptz','jsonb','jsonb','jsonb'], 'audited refresh RPC exists');
select has_function('public', 'of_mark_audit_degraded', array['jsonb'], 'audit degradation RPC exists');
select has_function('public', 'of_set_audit_degraded', array[]::text[], 'audit fallback marker RPC exists');
select has_function('public', 'of_get_control_runtime_state', array[]::text[], 'runtime compatibility RPC exists');
select has_function('public', 'of_get_migration_integrity', array[]::text[], 'migration integrity RPC exists');
select has_function('public', 'of_reconcile_execution_request', array['uuid','bigint'], 'request byte reconciliation RPC exists');
select has_function('public', 'of_finalize_execution', array['uuid','bigint','uuid','text','uuid','text','jsonb','timestamptz','jsonb','boolean'], 'idempotent execution finalization RPC exists');
select function_privs_are('public', 'of_get_instance_state', array[]::text[], 'service_role', array['EXECUTE'], 'service role can call state RPC');
select function_privs_are('public', 'of_get_instance_state', array[]::text[], 'anon', array[]::text[], 'anon cannot call state RPC');
select table_privs_are('one_fetch', 'admins', 'anon', array[]::text[], 'anon cannot read admins');
select table_privs_are('one_fetch', 'audit_events', 'authenticated', array[]::text[], 'authenticated cannot read audit');
select function_privs_are('public', 'of_change_password', array['uuid','uuid','text','text','jsonb'], 'anon', array[]::text[], 'anon cannot call password change RPC');
select function_privs_are('public', 'of_begin_login_attempt', array['text','text','jsonb'], 'anon', array[]::text[], 'anon cannot call login throttle RPC');
select function_privs_are('public', 'of_begin_auth_source_attempt', array['text','text','integer','jsonb'], 'anon', array[]::text[], 'anon cannot call auth source throttle RPC');
select function_privs_are('public', 'of_set_audit_degraded', array[]::text[], 'anon', array[]::text[], 'anon cannot mark audit degradation');
select function_privs_are('public', 'of_get_migration_integrity', array[]::text[], 'service_role', array['EXECUTE'], 'service role can read migration integrity');
select function_privs_are('public', 'of_get_migration_integrity', array[]::text[], 'anon', array[]::text[], 'anon cannot read migration integrity');
select function_privs_are('public', 'of_get_migration_integrity', array[]::text[], 'authenticated', array[]::text[], 'authenticated cannot read migration integrity');

select * from finish();
rollback;
