-- Generated by scripts/sync-migrations.mjs. Do not edit.
begin;
create extension if not exists pgtap with schema extensions;
select plan(2);

select is(
  (select count(*)::bigint from one_fetch.migration_history),
  9::bigint,
  'all migrations are recorded once'
);
select is(
  public.of_get_migration_integrity(),
  '[{"version":"202609040001","checksum":"39bb47b3c973b575676f5004ee1b018f466763102045fb1bece37f6d27bc0510"},{"version":"202609040002","checksum":"7dbc55c50491e9b508441a338966547a017d8210730daad13bb6f8c3f859d63f"},{"version":"202609040003","checksum":"3621e5ca5fe199a5d4fab73d7df9e450566c524b76f951e32ca5e8b567ca8546"},{"version":"202609040004","checksum":"87a661ff08ae6ea521512620d0121c3f4053286302119e0ed3bf8eb63448c1be"},{"version":"202609040005","checksum":"e643698c9dbf74acd57bf4d43b37b5edea4acc554b611bec461634c7ce90f592"},{"version":"202609040006","checksum":"4eb74e19ffff656e64d9e81797e67dca408e0d7f433d1f42e97bf0964a6ab791"},{"version":"202609040007","checksum":"b96eebcb63f0b69fdf46ea057f51c1928dac974591bf9b6365eca90c8efbc883"},{"version":"202609040008","checksum":"c3a66b2d1a4a5c0ea8694cfba655b5438c6d4b8cacf518bfed869d77fbafb265"},{"version":"202609040009","checksum":"925160ccb5c7ff9477e3b8034853690dcc0f239d358ff5c72af618b9ff2e5a71"}]'::jsonb,
  'database migration checksums match the shipped SQL bytes'
);

select * from finish();
rollback;
